version: "3.8"

services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: crud_app
      MARIADB_USER: cruduser
      MARIADB_PASSWORD: crudpass
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: cruduser
      DB_PASS: crudpass
      DB_NAME: crud_app
      LOG_DIR: /usr/src/app/logs
    volumes:
      - ./logs:/usr/src/app/logs
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

volumes:
  db_data:
